describe('Verify Login Failed', () => {
  beforeEach(() => {
    cy.visit('https://magento.softwaretestingboard.com/')
    })  
//TC Login Page -> Login Failed
    it("Login Failed - Email and Password Not Registered", () => {
      cy.contains("Sign In").click()
      cy.get('#email').type("cobaaku@mail.com")
      cy.get('#pass').type("Coba123")
      cy.get('#send2').click()
      cy.get('.message-error > div').should("be.visible")
      cy.get('.message-error > div').should("contain.text", 'The account sign-in was incorrect or your account is disabled temporarily.')
    });
  //TC Login Page -> Homepage - My Account page -> Edit Address Page
    it("Login Success - Can access Edit Address", () => {
      cy.contains("Sign In").click()
      cy.get('#email').type("akucoba@gmail.com")
      cy.get('#pass').type("Qwerty123")
      cy.get('#send2').click()
      cy.get('.logged-in').should("be.visible")
      cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
      cy.contains("My Account").click()
      cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').should('be.visible')
      cy.get('.box-billing-address > .box-content > address').should('be.visible')
      cy.get('.box-billing-address > .box-actions > .action > span').click()
      cy.url().should('include', '/customer/address/edit')
    });
  //TC Change Address Success
  it("Change Address Success", () => {
      cy.contains("Sign In").click()
      cy.get('#email').type("akucoba@gmail.com")
      cy.get('#pass').type("Qwerty123")
      cy.get('#send2').click()
      cy.get('.logged-in').should("be.visible")
      cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
      cy.contains("My Account").click()
      cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').should('be.visible')
      cy.get('.box-billing-address').should('be.visible')
      cy.get('.box-shipping-address').should('be.visible')
      cy.get('.box-billing-address > .box-content > address').should('be.visible')
      cy.get('.box-billing-address > .box-actions > .action > span').click()
      cy.url().should('include', '/customer/address/edit')
      cy.get('#firstname').clear()
      cy.get('#lastname').clear()
      cy.get('#company').clear()
      cy.get('#telephone').clear()
      cy.get('#street_1').clear()
      cy.get('#city').clear()
      cy.get('#region').clear()
      cy.get('#zip').clear()
      cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
      cy.get('#firstname-error').should('contain.text','This is a required field.')
      cy.get('#lastname-error').should('contain.text','This is a required field.')
      cy.get('#telephone-error').should('contain.text','This is a required field.')
      cy.get('#street_1-error').should('contain.text','This is a required field.')
      cy.get('#city-error').should('contain.text','This is a required field.')
      cy.get('#zip-error').should('contain.text','This is a required field.')
      cy.get('#firstname').type('Coba')
      cy.get('#lastname').type('Aku')
      cy.get('#company').type('Coba Aku')
      cy.get('#telephone').type('123456789')
      cy.get('#street_1').type('Jalan Coba')
      cy.get('#city').type('Jakarta Selatan')
      cy.get('#region').type('DKI Jakarta')
      cy.get('#zip').type('12345')
      cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
      cy.get('.message-success').should('be.visible')
      cy.get('.message-success').should('contain.text','You saved the address.')
    });
  });